---
# tasks file for lab
- name: Ensure packages "{{ base_packages }}" are installed
  dnf:
    name: "{{ base_packages }}"
    state: installed
    update_cache: yes
  become: yes

- name: Create lab pod
  containers.podman.podman_pod:
    name: lab
    state: started
    ports:
      - 3000:3000
      - 3010:3010
      - 9010:9010
      - 9080:9080
      
  become: yes

- name: install grafana
  include: grafana.yml

- name: install loki
  include: loki.yml

- name: install promtail
  include: promtail.yml